add esx:spawnVehicle callback
esx-framework/esx_core pull request #1007
Opened 2023-04-05 12:18 UTC by Taavi-AU

to spawn vehicles client side using a callback to server side spawn vehicles 👍

2023-04-05 12:19 UTC, Taavi-AU commented
make changes if you want to but better than handling vehicle spawn callbacks in each resource so esx should have one in core which is easier.

2023-04-05 12:19 UTC, Taavi-AU commented
fantik thats your **job**

2023-06-13 22:32 UTC, Gellipapa requested changes

2023-06-13 22:32 UTC, Gellipapa commented on [core]/es_extended/server/main.lua
> +      while GetVehiclePedIsIn(ped) ~= vehicle do
If will never be equal will run forever?

This should be an attempt for say 15 if it fails then break.

2023-06-16 23:24 UTC, Gellipapa commented
@Taavi-AU Hi! Can you make requested changes?

2023-06-20 18:10 UTC, Gellipapa commented on [core]/es_extended/server/main.lua
>    local ped = GetPlayerPed(source)
Please handle if vehData is nil and vehData is table (we accept only table type) cb false and add log how "VehData is nil, please add vehData then parameters".

2023-06-20 18:11 UTC, Gellipapa commented
@tony-stark-17 Hi! Thank you for fast work, please fix this request and i can merge good job, thank you :)

2023-06-20 18:12 UTC, TheFantomas commented
> @tony-stark-17 Hi! Thank you for fast work, please fix this request and i can merge good job, thank you :)

+ Please handle formatting of this callback :D 4 spaces please

2023-06-21 11:13 UTC, Taavi-AU commented
is that good, formatted, anything else?

2023-06-21 11:18 UTC, Taavi-AU commented
example

```lua
ESX.TriggerServerCallback("esx:spawnVehicle", function(vehicleId)
	print(vehicleId)
end, {`ZENTORNO`, vector4(0.0, 0.0, 0.0, 180.0), {plate = "TEST123"}, true})
```

2023-06-21 11:22 UTC, Taavi-AU commented
example

```lua
ESX.TriggerServerCallback("esx:spawnVehicle", function(vehicleId)
	print(vehicleId)
end, {model = `ADDER`, coords = vector4(0.0, 0.0, 0.0, 180.0), props = {plate = "TEST123"}, warp = true})
```

2023-06-21 17:04 UTC, Gellipapa commented on [core]/es_extended/server/main.lua
> +        local vehicle = NetworkGetEntityFromNetworkId(id)
If vehData.wrap true  only use 

local vehicle = NetworkGetEntityFromNetworkId(id)

please put this if statement  thank you.

2023-06-21 17:10 UTC, Gellipapa commented on [core]/es_extended/server/main.lua
> +        local vehicle = NetworkGetEntityFromNetworkId(id)
@Taavi-AU Please do this change.

2023-06-22 08:32 UTC, Gellipapa approved these changes
It's okey, thank you. Looks cool.

2023-06-22 08:33 UTC, merged