Update tr.lua
esx-framework/esx_core pull request #1024
Opened 2023-04-21 13:33 UTC by Gold14567

2023-04-21 17:35 UTC, CsokiHUN approved these changes

2023-06-13 22:28 UTC, Gellipapa requested changes
Hi! @Gold14567  Please fix gaps.
![image](https://github.com/esx-framework/esx_core/assets/22717950/45e460ab-4073-4b34-9554-ac5cbe3caac6)

2023-06-16 23:28 UTC, Gellipapa commented
@Gold14567 Hi! Please resolve merge conflict and fix requested changes.

2023-06-17 09:15 UTC, TheFantomas commented
Hello,

At the moment, we only accepts locale prs from our translators who have created a ticket on our discord. We have 16 languages and 25 translators.
You too can become one of the translators and translate all existing scripts into Turkish.

Just create a ticket on our discord: https://discord.gg/esx-framework-513374574394474531

At the moment, however, this pr will not be accepted.
Thanks for trying to help anyway.

With regards and respect
Management
@TheFantomas

2023-06-17 09:15 UTC, closed without merging