refactor(xPlayer): delete getMeta error message
esx-framework/esx_core pull request #1037
Opened 2023-05-03 21:42 UTC by CENSOR1337

getMeta no longer prints an error message on the index did not exist condition.

2023-05-12 08:22 UTC, CsokiHUN commented
why?

2023-06-07 13:12 UTC, NikartikTheBear commented
I believe he meant why would you remove that

2023-06-13 22:15 UTC, Gellipapa commented
@CENSOR1337 Hi! Where use hasMeta? 

So not being used anywhere but just an option no one will use it but rely on getMeta() ~= nil or similar checks so I don't think it makes sense to implement it. 

Instead, you could have something that if the server is in debug mode then print returns getMeta with nil of course but then you have debug print which is useful for development.

2023-06-14 09:53 UTC, CENSOR1337 commented
> @CENSOR1337 Hi! Thank you, I think we can refactor this code to be fully recursive, so the subIndex part could be replaced by a recursive function call and the code wouldn't be so complex. I know you didn't do this, but you are currently modifying this part of the code.

I have made a change base on your suggestion and maintenance a little bit of code flow, to make it easier to read.
Let me know what you think, Thanks.

2023-06-14 16:45 UTC, Gellipapa commented on [core]/es_extended/server/classes/player.lua
> +        if (metadata == nil) then
if not metadata then better.

2023-06-14 16:49 UTC, Gellipapa commented on [core]/es_extended/server/classes/player.lua
> +                    returnValues[key] = self.getMeta(index, key)
key is table break code. You should handle only string.

2023-06-14 16:50 UTC, Gellipapa requested changes
Nice so clean better than before version.

2023-06-14 20:24 UTC, Gellipapa approved these changes
Good job, thank you for help.

2023-06-14 20:25 UTC, merged