Save Custom Wheels
esx-framework/esx_core pull request #1060
Opened 2023-06-09 09:38 UTC by TheKetur55

2023-06-09 20:26 UTC, falszywyyy approved these changes
Looks good!

2023-06-13 21:40 UTC, Gellipapa requested changes

2023-06-13 21:40 UTC, Gellipapa commented on [core]/es_extended/client/functions.lua
> +         SetVehicleMod(vehicle, 23, props.modFrontWheels, true)
Hi! This is bad,  you should use "props.modCustomWheels". I think is typo, please fix this typo.

2023-06-18 18:50 UTC, Gellipapa approved these changes

2023-06-18 18:51 UTC, merged