Security Enhancement: Distance Check for 'esx:onPickup' Event
esx-framework/esx_core pull request #1161
Opened 2023-08-20 03:52 UTC by Kenshiin13

### Security Enhancement: Distance Check for 'esx:onPickup' Event

#### Description

This pull request introduces a critical security update for the "esx:onPickup" event to mitigate potential abuses. The update incorporates a distance check mechanism, preventing players from exploiting the event to collect pickups from excessive distances. This measure ensures fair gameplay and maintains the integrity of the event.

#### Changes Made

- Store serverside pickup coords as a vector, eliminating the need for client-side conversion, and allowing for arithmetic operations on them. 
- Implemented a distance check within the existing 'esx:onPickup' event handling code.
- If a player attempts to interact with a pickup beyond a specified distance (5.0 units), a warning is triggered, and the interaction is blocked.

The modified code snippet is as follows:
```lua
RegisterNetEvent('esx:onPickup')
AddEventHandler('esx:onPickup', function(pickupId)
    local pickup, xPlayer, success = Core.Pickups[pickupId], ESX.GetPlayerFromId(source)

    if pickup then
        local playerPickupDistance = #(pickup.coords - xPlayer.getCoords(true))
        if(playerPickupDistance > 5.0) then
            print(('[^3WARNING^7] Player Detected Cheating (Out of range pickup): ^5%s^7'):format(xPlayer.getIdentifier()))
            return
        end

        -- Rest of the original event handling code

        if success then
            Core.Pickups[pickupId] = nil
            TriggerClientEvent('esx:removePickup', -1, pickupId)
        end
    end
end)
```

#### Reasoning

This security update is vital to prevent potential abuses of the "esx:onPickup" event. The event could potentially be exploited by malicious players to trigger unauthorized pickups using a simple code snippet like this:
```lua
RegisterNetEvent("esx:createPickup", function(pickupId)
    TriggerServerEvent("esx:onPickup", pickupId)
end)
 ```
By implementing a distance check, the update ensures that players can only interact with pickups within a reasonable range, discouraging unauthorized collection of pickups from afar.

#### Counterargument Consideration:

It's worth addressing the potential counterargument that the distance check might be unnecessary due to a player's ability to teleport to pickups, thus eliminating the need for this change. However, it's essential to recognize that third-party anticheats are designed precisely to identify players employing teleportation tactics across the map. Additionally, the presence of one form of vulnerability should not overshadow addressing another potential attack vector.

Thank you for considering these enhancements. Your feedback and suggestions are appreciated.

2023-08-20 04:25 UTC, iSentrie requested changes
this will require decrease in vector z, else player won't be able to pick anything from ground

```lua
TriggerEvent('esx:createPickup', pickupId, pickup.label, pickup.coords - vector3(0, 0, 0.5), pickup.type, pickup.name, pickup.components, pickup.tintIndex)
```

however, who don't use ox_inventory, after client restart missing pickups will appear floating in the air, needs an better fix, but for now at least it will work. currently in last version missing pickups wasn't working at all.

2023-08-20 04:30 UTC, Kenshiin13 commented
> this will require decrease in vector z, else player won't be able to pick anything from ground

Haven't tested that tbh. The pickups spawned properly on the ground when I tested the vulnerability. I can push another commit tho if requested.

2023-08-20 04:34 UTC, iSentrie commented
i tested, that's why i wrote it

2023-08-20 04:37 UTC, Kenshiin13 commented
> your changes fixes the error

My changes have nothing to do with that.

2023-08-20 04:41 UTC, iSentrie commented
> > your changes fixes the error
> 
> My changes have nothing to do with that.

without your changes missing pickups won't spawn at all, resulting in an error in client console.
you fixed it without knowing it.
it was fixed before by someone and then broken again by someone, now you fixed it again.

2023-08-20 10:56 UTC, Gellipapa commented
@Kenshiin13 Hi! Could you write in to accept coordinates not just the current coordinate? 
Example: I need to tell you that I want a pickup points xyz, because currently it only looks at your current coordinate to the best of my knowledge.

2023-08-20 12:51 UTC, Kenshiin13 commented
> @Kenshiin13 Hi! Could you write in to accept coordinates not just the current coordinate? Example: I need to tell you that I want a pickup points xyz, because currently it only looks at your current coordinate to the best of my knowledge.

I'm sorry, I'm not sure what you mean. Why would we test against anything other than the players current coordinates to determine whether a pickup request ist legitmate or not?

2023-08-20 16:14 UTC, Gellipapa commented
> 
I seem to remember that currently in ESX there is no option to spawn a pickup point to a given coordinate, you can only spawn a point to the player's coordinate. That's what I was thinking about, that I should be able to spawn a pickup point to a custom coordinate.

2023-08-20 16:56 UTC, Kenshiin13 commented
> > 
> 
> I seem to remember that currently in ESX there is no option to spawn a pickup point to a given coordinate, you can only spawn a point to the player's coordinate. That's what I was thinking about, that I should be able to spawn a pickup point to a custom coordinate.

You mean like this 92d6f49464fbffc2f5431c06f560637eb457302a?

2023-08-20 17:04 UTC, Gellipapa commented
@Kenshiin13 Yes, thank you.

2023-08-20 17:05 UTC, Gellipapa commented
Thanks for the PR, we will test it soon and if it works we will merge it.

2023-08-23 18:20 UTC, Gellipapa commented
@Kenshiin13 Hi! I tested this pr and i found bug.

- ESX.CreatePickup method first parameter is type (this is not correct name, please fix) and this is name overwrite default lua type checker and i get nil value if i try run this code. (Please rename all type parameter to other name in server/main.lua)

Let's find a solution so that if I don't want to spawn a weapon, I don't have to specify "components" and "tintIdex", because I currently have to specify them because coordinates are included and the parameter number of pieces makes it mandatory to specify them.  **(!!We have to pay attention to backwards compatibility because it is not easy to do this.)**


![image](https://github.com/esx-framework/esx_core/assets/22717950/89892854-54d6-40e5-8267-8be63afbe5c1)

2023-08-23 18:23 UTC, Gellipapa requested changes

2023-08-23 18:23 UTC, Gellipapa commented on [core]/es_extended/server/functions.lua
> +	function ESX.CreatePickup(type, name, count, label, playerId, components, tintIndex, coords)
Rename type parameter because overwrite default lua type checker method.

2023-08-23 18:24 UTC, Gellipapa commented
In the future, please make sure that it is tested, because this is a basic bug that could have been fixed in the first test. Thanks.

2023-08-23 18:28 UTC, Kenshiin13 commented
> Let's find a solution so that if I don't want to spawn a weapon, I don't have to specify "components" and "tintIdex", because I currently have to specify them because coordinates are included and the parameter number of pieces makes it mandatory to specify them. **(!!We have to pay attention to backwards compatibility because it is not easy to do this.)**
> 
> ![image](https://user-images.githubusercontent.com/22717950/262762682-89892854-54d6-40e5-8267-8be63afbe5c1.png)

Well, I am not sure if there is a way to do this without breaking backwards-compatibility.

2023-08-23 18:35 UTC, Gellipapa commented
> > Let's find a solution so that if I don't want to spawn a weapon, I don't have to specify "components" and "tintIdex", because I currently have to specify them because coordinates are included and the parameter number of pieces makes it mandatory to specify them. **(!!We have to pay attention to backwards compatibility because it is not easy to do this.)**
> 
> Well, I am not sure if there is a way to do this without breaking backwards-compatibility.

If you have any ideas, feel free to write them down, I can't think of anything right now, if we don't have a solution, it will stay as it was.

2023-08-23 19:12 UTC, Kenshiin13 commented
> If you have any ideas, feel free to write them down, I can't think of anything right now, if we don't have a solution, it will stay as it was. I mean that part will not be changed.

Nope, not really. Does that work for you? https://github.com/esx-framework/esx_core/pull/1161/commits/1b27475ce16abbee6aeec606f9bf123069b5f081

2023-08-23 19:14 UTC, Kenshiin13 commented on [core]/es_extended/server/functions.lua
> +	function ESX.CreatePickup(type, name, count, label, playerId, components, tintIndex, coords)
https://github.com/esx-framework/esx_core/pull/1161/commits/1b27475ce16abbee6aeec606f9bf123069b5f081

2023-08-23 19:24 UTC, Gellipapa commented
> > If you have any ideas, feel free to write them down, I can't think of anything right now, if we don't have a solution, it will stay as it was. I mean that part will not be changed.
> 
> Nope, not really. Does that work for you? [1b27475](https://github.com/esx-framework/esx_core/commit/1b27475ce16abbee6aeec606f9bf123069b5f081)

I will check soon.

2023-08-25 15:42 UTC, Gellipapa commented
Hi! Well done, I was tested and merged.

2023-08-25 15:43 UTC, Gellipapa approved these changes

2023-08-25 15:43 UTC, merged