feat(es_extended/client/blips): add Blip class
esx-framework/esx_core pull request #1490
Opened 2024-11-19 15:49 UTC by btwlouis

This pull request introduces a new `Blip` class to simplify the management of blips. The class encapsulates all functionalities related to blip creation, updates, and deletion, providing an easy-to-use interface for developers.

# Benefits
- Simplifies blip management
- Improves readability and maintainability of the codebase
- Reduces code repetition by encapsulating blip operations into reusable methods

# Example:

```lua
CreateThread(function()
    local blip = ESX.Blip:new({
        coords = vec3(202.50, -841.45, 30.67),
        sprite = 23,
        colour = 2,
        label = "Test Blip",
        scale = 1.5,
        display = 4,
        shortRange = true
    })

    Wait(1000)

    blip:setColour(3)

    Wait(1000)

    blip:setLabel("Test Blip 2")

    Wait(1000)

    blip:setScale(2.0)

    Wait(1000)

    blip:setDisplay(2)

    Wait(1000)

    blip:setShortRange(false)

    Wait(1000)

    blip:setCoords(vec3(202.50, -845.45, 30.67))
end)
```

# Impact on Existing Code
This addition is fully backward-compatible. It does not alter any existing functionality within the framework but provides a modular approach for future blip-related operations.

# Next Steps
- Extend the `Blip` class with more options to modfiy a blip

2024-11-19 16:14 UTC, Mycroft-Studios commented on [core]/es_extended/imports.lua
> -            local fn, err = load(file, ('@@es_extended/%s'):format(path))
This should remain the same

2024-11-19 16:16 UTC, Arctos2win requested changes
put the whole logic into the imports file no need to have internal functions on this one.

2024-11-24 15:41 UTC, Kenshiin13 commented
@Arctos2win

2024-12-04 16:36 UTC, Kenshiin13 commented
Hey @btwlouis,

Thank you for your contribution! After careful consideration and discussion with the team, we've decided that this feature isn't needed at the moment. We really appreciate the effort you put into it and hope you'll continue contributing in the future. Thank you again!

2024-12-04 16:36 UTC, closed without merging