feat(es_extended): Extra callback functions
esx-framework/esx_core pull request #1505
Opened 2024-11-25 19:15 UTC by Mycroft-Studios

Introduces 2 new functions:
`ESX.DoesClientCallbackExist`
`ESX.DoesServerCallbackExist`

2024-11-25 19:34 UTC, Kenshiin13 commented
I don't see the point of this. ESX already throws an error if a resource attempts to access an invalid callback. This just promotes people calling `ESX.DoesServerCallbackExist` and `ESX.DoesClientCallbackExist` before every damn callback.

Third party resources can check if their dependencies are started and just assume that all expected callbacks are registered. We are already letting them know if they are not ^^

2024-11-25 19:45 UTC, Arctos2win commented
> I don't see the point of this. ESX already throws an error if a resource attempts to access an invalid callback. This just promotes people calling `ESX.DoesServerCallbackExist` and `ESX.DoesClientCallbackExist` before every damn callback.
> 
> Third party resources can check if their dependencies are started and just assume that all expected callbacks are registered. We are already letting them know if they are not ^^

I agree with Kenshin on this one, there is 0 usecase for it and litterly no one ever requested a functionality like this 
in the so many years this project exists.

2024-11-25 21:21 UTC, Kenshiin13 requested changes

2024-11-25 21:21 UTC, Kenshiin13 commented on [core]/es_extended/client/modules/callback.lua
> +end
This doesn't need to be a thing

2024-11-25 21:21 UTC, Kenshiin13 commented on [core]/es_extended/server/modules/callback.lua
> +end
This doesn't need to be a thing

2024-12-03 15:47 UTC, Kenshiin13 commented
@Mycroft-Studios

2024-12-03 22:59 UTC, Kenshiin13 approved these changes
LGTM!

2024-12-03 22:59 UTC, merged