fix(esx-legacy): Updated/added es translations & changed the default sql files from fr to en
esx-framework/esx_core pull request #762
Opened 2022-12-21 11:54 UTC by paarbo

2022-12-21 23:11 UTC, Gellipapa commented
Hi! Thank you for help @paarbo but check and delete the unnecessary spaces thanks. Once this is done I merge pr.

2022-12-30 18:57 UTC, TheFantomas requested changes
Please update all es.lua to newest version. Like en.lua :D Because a few things have already been removed a long time ago :D For example like this
![image](https://user-images.githubusercontent.com/117121911/210103691-226b19a8-4b20-4e6f-ad07-1f0efa42b611.png)

2022-12-30 21:49 UTC, TheFantomas approved these changes

2022-12-31 03:02 UTC, Gellipapa commented
> Also I have included in this request, some improvements to the server.cfg. (These changes have been also pushed to the esx-recipe)

Hi! @paarbo! Okey thanks for completing the server cfg. It is being reviewed and will be available soon.

2023-01-09 22:20 UTC, Gellipapa reviewed
Please fixes all review comments.

2023-01-09 22:20 UTC, Gellipapa commented on [esx_addons]/esx_ambulancejob/esx_ambulancejob.sql
>  INSERT INTO `addon_account` (name, label, shared) VALUES
Default SQL please do not edit! Replace with the original.

2023-01-09 22:20 UTC, Gellipapa commented on [esx_addons]/esx_ambulancejob/localization/en_esx_ambulancejob.sql
> -
Please don't remove EN version!

2023-01-09 22:20 UTC, Gellipapa commented on [esx_addons]/esx_bankerjob/localization/en_esx_bankerjob.sql
> -
Please don't remove EN version!

2023-01-09 22:20 UTC, Gellipapa commented on [esx_addons]/esx_animations/localization/en_config.lua
> -Config = {}
Please don't remove EN version!

2023-01-09 23:43 UTC, TheFantomas commented
Why dont remove en version? He move en version to "default sql version" and move default sql to france :D Because default sql is  in french :D

2023-01-09 23:47 UTC, Gellipapa commented
> 

I know it's just distracting, I'll delete it :)

2023-01-10 17:08 UTC, Gellipapa commented
> > > 
> > 
> > 
> > I know it's just distracting, I'll delete it :)
> 
> All sql's files outside of localization folder will be deleted? @Gellipapa

The point is that the default SQL should not be in the locales folder and should be the default script name. As is the default when you look at a script.

2023-01-10 19:35 UTC, Gellipapa commented
> > > > > 
> > > > 
> > > > 
> > > > I know it's just distracting, I'll delete it :)
> > > 
> > > 
> > > All sql's files outside of localization folder will be deleted? @Gellipapa
> > 
> > 
> > The point is that the default SQL should not be in the locales folder and should be the default script name. As is the default when you look at a script.
> 
> Then I don't see the point of restoring the deleted sql files that you asked

If you can solve it the way it was in the original, there's no question of how to solve it.

2023-01-18 14:18 UTC, closed without merging