feat: Metadata
esx-framework/esx_core pull request #912
Opened 2023-02-21 22:22 UTC by Rav3n95

2023-02-21 22:31 UTC, CsokiHUN requested changes

2023-02-21 22:31 UTC, CsokiHUN commented on [core]/es_extended/server/main.lua
> +  print(json.encode(loadPlayer,{indent=true}))
remove debug print :)

2023-02-22 09:10 UTC, CsokiHUN approved these changes
looks good

2023-02-22 09:17 UTC, Gellipapa commented
Really cool, but a log system would be better than using prints, and if I have metadata then how can I update the value of a given key? So I don't want the whole table just one value of it, if I saw it right it allows to add table as metadata.

2023-02-22 09:19 UTC, CsokiHUN commented
> Really cool, but a log system would be better than using prints, and if I have metadata then how can I update the value of a given key? So I don't want the whole table just one value of it, if I saw it right it allows to add table as metadata.

```lua
xPlayer.setMeta('your_key', value)
```

So you are not updating the whole key, only the value for that key.

2023-02-22 09:25 UTC, Gellipapa commented
> 

What happens if I add table as value how do I update the value? 
{bread = 200, water = 300} 
i would like the water to be only 400 the correct output would be: {bread = 200, water = 400}.

2023-02-22 09:30 UTC, Gellipapa commented
Another feature, I want to retrieve a value from a table, how do I do that? 

key: table_data
value {bread:200, water:300}

I'm only interested in the water value? How can I get it? 

getMeta(table_data, "water") --> output: 300. 

I think such an option could be in getter, of course it would only work for table.

2023-02-22 09:31 UTC, CsokiHUN commented
> What happens if I add table as value how do I update the value? table_data = {bread = 200, water = 300} key: table_data value: {bread = 200, water = 300} i would like the water to be only 400 the correct output would be: {bread = 200, water = 400}.

I understand what you are saying, but I don't think we can do it well. Because what if someone uses a non-string key at the table.. 
It's not that big of a problem if the whole table needs to be updated, because we're not going to store a lot of data here.

2023-02-22 09:31 UTC, Rav3n95 commented
What if the stored value it's not a table?

2023-02-22 09:32 UTC, CsokiHUN commented
If we include the option to retrieve the value of the key from the table, we are in the same place as if we had done it ourselves

2023-02-22 09:32 UTC, Gellipapa commented
> Then you get the index of the data, update it yourself, then send the updated table back. That's why I posted in Dev branch, if you have a idea how to fix this issue whit out using the getter first. Go for it :D


A possible solution, with an optional parameter, is to use only a table because you can update a not a table value.
For example: setMeta(table_data,'water', 400)

2023-02-22 09:34 UTC, Gellipapa commented
> If it is not a table you return the given key value.

2023-02-22 09:35 UTC, Rav3n95 commented
Show me the code then :D

2023-02-22 09:36 UTC, Gellipapa commented
> If we include the option to retrieve the value of the key from the table, we are in the same place as if we had done it ourselves

It is better than always having to retrieve and index everything. Of course there is also an indexing in the background but it is in the background. It is more practical to have the option to return a specific value or the whole table. 

These are just the features and ideas I threw in here :)

2023-02-22 09:37 UTC, Rav3n95 commented
`xPlayer.setMeta('bikes', {'20', '24', '26', '27.5', '28', '29'})` How about a not indexed table value?

2023-02-22 09:55 UTC, CsokiHUN commented
> xPlayer.setMeta('bikes', {'20', '24', '26', '27.5', '28', '29'}) How about a not indexed table value?

fun fact: you store the numbers as string 😂

2023-02-22 10:00 UTC, Gellipapa commented
![image](https://user-images.githubusercontent.com/22717950/220586704-620c4e53-48dc-49c7-a1c1-70288d9b419b.png)

This is core logic. Need nil handler etc.

```lua

local function printTable( t )
 
    local printTable_cache = {}
 
    local function sub_printTable( t, indent )
 
        if ( printTable_cache[tostring(t)] ) then
            print( indent .. "*" .. tostring(t) )
        else
            printTable_cache[tostring(t)] = true
            if ( type( t ) == "table" ) then
                for pos,val in pairs( t ) do
                    if ( type(val) == "table" ) then
                        print( indent .. "[" .. pos .. "] => " .. tostring( t ).. " {" )
                        sub_printTable( val, indent .. string.rep( " ", string.len(pos)+8 ) )
                        print( indent .. string.rep( " ", string.len(pos)+6 ) .. "}" )
                    elseif ( type(val) == "string" ) then
                        print( indent .. "[" .. pos .. '] => "' .. val .. '"' )
                    else
                        print( indent .. "[" .. pos .. "] => " .. tostring(val) )
                    end
                end
            else
                print( indent..tostring(t) )
            end
        end
    end
 
    if ( type(t) == "table" ) then
        print( tostring(t) .. " {" )
        sub_printTable( t, "  " )
        print( "}" )
    else
        sub_printTable( t, "  " )
    end
end


local metadata = {
  ["table_data"] = {bread =  200, water =  300}
}

function getMeta(key, searchedKey)
  if type(metadata[key]) == 'table' and searchedKey then
    return metadata[key][searchedKey]
  end
  return metadata[key]
end

function setMeta(key, value, newValue)
  if type(metadata[key]) == 'table' and newValue then
    metadata[key][value] = newValue
    return
  end
  metadata[key] = value
end

print("GET DEFAULT VALUES")
printTable(getMeta("table_data"))
print("SET NEW VALUE ONLY WATER TO 600")
setMeta("table_data", "water", 600)
print("GET ONLY WATER VALUE")
printTable(getMeta("table_data","water"))
print("------------------------------------")
print("DEFAULT SET VERSION WORKS {bread =  200, water =  300}")
setMeta("table_data", {bread =  200, water =  300})
print("GET DEFAULT VALUES")
printTable(getMeta("table_data"))



 ```

2023-02-22 10:04 UTC, Gellipapa commented
> 

You can do index, but why do this or you can use default version can set all table -> backwards compatiblity. Sorry guys i should go to work.

2023-02-22 10:07 UTC, Gellipapa commented
Next level if i can search in one value, why can't we pass it a table if i only need 5 out of 20 values, same with update, it would be nice to update those 5 values in order. 👍

2023-02-22 11:35 UTC, Rav3n95 commented
Also play a violin and a guitar in a same time ;)

2023-02-22 11:58 UTC, Rav3n95 commented
`
RegisterCommand('meta', function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    print('--------------------------------------------')
    print('Clearing "shopPrices" meta')
    xPlayer.clearMeta('shopPrices')
    print('First meta getter')
    print(json.encode(xPlayer.getMeta(),{indent=true}))
    print('--------------------------------------------')
    print('Setting "shopPrices" meta')
    xPlayer.setMeta('shopPrices', {bread = 200, water = 300})
    print('--------------------------------------------')
    print('Second meta getter')
    print(json.encode(xPlayer.getMeta(),{indent=true}))
    print('--------------------------------------------')
    print('Setting "bread" value on "shopPrices" meta')
    xPlayer.setMeta('shopPrices', 'bread', 250)
    print('Third meta getter -> just getting the bread price')
    print(xPlayer.getMeta('shopPrices', 'bread'))
    print('--------------------------------------------')
    print('Forth meta getter')
    print(json.encode(xPlayer.getMeta(),{indent=true}))
end, false)
`

2023-02-22 12:08 UTC, Gellipapa approved these changes
Nice good job, thank you buddy. 👍

2023-02-22 13:24 UTC, TheFantomas approved these changes

2023-02-26 19:31 UTC, gerung commented
cool, its posible to direct save when set meta?

2023-02-26 19:54 UTC, Rav3n95 commented
> cool, its posible to direct save when set meta?

If you are using the ESX.Saveplayer() function after you set the meta 🤣

2023-02-26 20:07 UTC, gerung commented
> > cool, its posible to direct save when set meta?
> 
> If you are using the ESX.Saveplayer() function after you set the meta 🤣

i just set player detail (first lastname, bod, sex, height, etc) as a meta, but i have issue when get the meta, give me nil value
```
GetCharacters = function(source,data,slots)
	local characters = {}
	local license = ESX.GetIdentifier(source)
	local id = Config.Prefix..'%:'..license
	local data = MySQL.query.await('SELECT * FROM users WHERE identifier LIKE ?', {'%'..id..'%'})
	if data then
		for k,v in pairs(data) do
			local job, grade = v.job or 'imigran', tostring(v.job_grade)
			local accounts = json.decode(v.accounts)
			local id = tonumber(string.sub(v.identifier, #Config.Prefix+1, string.find(v.identifier, ':')-1))
			local xPlayer = ESX.GetPlayerFromId(source)
			print(xPlayer.getMeta('detail','firstname'))
		end
	end
	return {characters = characters , slots = slots}
end
```

2023-02-26 20:12 UTC, Gellipapa commented
> > > cool, its posible to direct save when set meta?
> > 
> > 
> > If you are using the ESX.Saveplayer() function after you set the meta 🤣
> 
> i just set player detail (first lastname, bod, sex, height, etc) as a meta, but i have issue when get the meta, give me nil value
> 
> ```lua
> GetCharacters = function(source,data,slots)
> 	local characters = {}
> 	local license = ESX.GetIdentifier(source)
> 	local id = Config.Prefix..'%:'..license
> 	local data = MySQL.query.await('SELECT * FROM users WHERE identifier LIKE ?', {'%'..id..'%'})
> 	if data then
> 		for k,v in pairs(data) do
> 			local job, grade = v.job or 'imigran', tostring(v.job_grade)
> 			local accounts = json.decode(v.accounts)
> 			local id = tonumber(string.sub(v.identifier, #Config.Prefix+1, string.find(v.identifier, ':')-1))
> 			local xPlayer = ESX.GetPlayerFromId(source)
> 			print(xPlayer.getMeta('detail','firstname'))
> 		end
> 	end
> 	return {characters = characters , slots = slots}
> end
> ```

Hi! If you print json.encode(xPlayer.getMeta('detail')) what is get?

2023-02-26 20:14 UTC, gerung commented
> > > > cool, its posible to direct save when set meta?
> > > 
> > > 
> > > If you are using the ESX.Saveplayer() function after you set the meta 🤣
> > 
> > 
> > i just set player detail (first lastname, bod, sex, height, etc) as a meta, but i have issue when get the meta, give me nil value
> > ```lua
> > GetCharacters = function(source,data,slots)
> > 	local characters = {}
> > 	local license = ESX.GetIdentifier(source)
> > 	local id = Config.Prefix..'%:'..license
> > 	local data = MySQL.query.await('SELECT * FROM users WHERE identifier LIKE ?', {'%'..id..'%'})
> > 	if data then
> > 		for k,v in pairs(data) do
> > 			local job, grade = v.job or 'imigran', tostring(v.job_grade)
> > 			local accounts = json.decode(v.accounts)
> > 			local id = tonumber(string.sub(v.identifier, #Config.Prefix+1, string.find(v.identifier, ':')-1))
> > 			local xPlayer = ESX.GetPlayerFromId(source)
> > 			print(xPlayer.getMeta('detail','firstname'))
> > 		end
> > 	end
> > 	return {characters = characters , slots = slots}
> > end
> > ```
> 
> Hi! If you print json.encode(xPlayer.getMeta('detail')) what is get?

![image](https://user-images.githubusercontent.com/64629964/221434741-8c674662-830b-4d93-a882-bacd5c125ddb.png)

2023-02-26 20:49 UTC, gerung commented
> > > > cool, its posible to direct save when set meta?
> > > 
> > > 
> > > If you are using the ESX.Saveplayer() function after you set the meta 🤣
> > 
> > 
> > i just set player detail (first lastname, bod, sex, height, etc) as a meta, but i have issue when get the meta, give me nil value
> > ```lua
> > GetCharacters = function(source,data,slots)
> > 	local characters = {}
> > 	local license = ESX.GetIdentifier(source)
> > 	local id = Config.Prefix..'%:'..license
> > 	local data = MySQL.query.await('SELECT * FROM users WHERE identifier LIKE ?', {'%'..id..'%'})
> > 	if data then
> > 		for k,v in pairs(data) do
> > 			local job, grade = v.job or 'imigran', tostring(v.job_grade)
> > 			local accounts = json.decode(v.accounts)
> > 			local id = tonumber(string.sub(v.identifier, #Config.Prefix+1, string.find(v.identifier, ':')-1))
> > 			local xPlayer = ESX.GetPlayerFromId(source)
> > 			print(xPlayer.getMeta('detail','firstname'))
> > 		end
> > 	end
> > 	return {characters = characters , slots = slots}
> > end
> > ```
> 
> Hi! If you print json.encode(xPlayer.getMeta('detail')) what is get?

works, i need to define like this
local meta = xPlayer.getMeta('detail') and meta.firstname, etc.  but i get a new issue, when i try to logout, i get the same issue

2023-02-26 20:52 UTC, gerung commented
> > > > cool, its posible to direct save when set meta?
> > > 
> > > 
> > > If you are using the ESX.Saveplayer() function after you set the meta 🤣
> > 
> > 
> > i just set player detail (first lastname, bod, sex, height, etc) as a meta, but i have issue when get the meta, give me nil value
> > ```lua
> > GetCharacters = function(source,data,slots)
> > 	local characters = {}
> > 	local license = ESX.GetIdentifier(source)
> > 	local id = Config.Prefix..'%:'..license
> > 	local data = MySQL.query.await('SELECT * FROM users WHERE identifier LIKE ?', {'%'..id..'%'})
> > 	if data then
> > 		for k,v in pairs(data) do
> > 			local job, grade = v.job or 'imigran', tostring(v.job_grade)
> > 			local accounts = json.decode(v.accounts)
> > 			local id = tonumber(string.sub(v.identifier, #Config.Prefix+1, string.find(v.identifier, ':')-1))
> > 			local xPlayer = ESX.GetPlayerFromId(source)
> > 			print(xPlayer.getMeta('detail','firstname'))
> > 		end
> > 	end
> > 	return {characters = characters , slots = slots}
> > end
> > ```
> 
> Hi! If you print json.encode(xPlayer.getMeta('detail')) what is get?

![image](https://user-images.githubusercontent.com/64629964/221436598-03b88ea4-7a4e-4508-97e4-ab2748254a86.png)
still error

2023-02-26 21:46 UTC, Rav3n95 commented
> > > > > cool, its posible to direct save when set meta?
> > > > 
> > > > 
> > > > If you are using the ESX.Saveplayer() function after you set the meta 🤣
> > > 
> > > 
> > > i just set player detail (first lastname, bod, sex, height, etc) as a meta, but i have issue when get the meta, give me nil value
> > > ```lua
> > > GetCharacters = function(source,data,slots)
> > > 	local characters = {}
> > > 	local license = ESX.GetIdentifier(source)
> > > 	local id = Config.Prefix..'%:'..license
> > > 	local data = MySQL.query.await('SELECT * FROM users WHERE identifier LIKE ?', {'%'..id..'%'})
> > > 	if data then
> > > 		for k,v in pairs(data) do
> > > 			local job, grade = v.job or 'imigran', tostring(v.job_grade)
> > > 			local accounts = json.decode(v.accounts)
> > > 			local id = tonumber(string.sub(v.identifier, #Config.Prefix+1, string.find(v.identifier, ':')-1))
> > > 			local xPlayer = ESX.GetPlayerFromId(source)
> > > 			print(xPlayer.getMeta('detail','firstname'))
> > > 		end
> > > 	end
> > > 	return {characters = characters , slots = slots}
> > > end
> > > ```
> > 
> > 
> > Hi! If you print json.encode(xPlayer.getMeta('detail')) what is get?
> 
> ![image](https://user-images.githubusercontent.com/64629964/221436598-03b88ea4-7a4e-4508-97e4-ab2748254a86.png) still error, fyi: i have string and number value on detail meta

Why don't you use the data from sql? v.meta its there is v.job

2023-02-26 21:48 UTC, Rav3n95 commented
Also you have a modified server bud, don't be surprise.

2023-02-26 22:01 UTC, Gellipapa commented
@gerung It's works perfectly, i think you've got the problem.
![image](https://user-images.githubusercontent.com/22717950/221440070-2c785cef-3864-4510-83b3-d2b95744e90e.png)

2023-02-26 22:11 UTC, merged

2023-02-27 01:34 UTC, gerung commented
> @gerung It's works perfectly, i think you've got the problem. ![image](https://user-images.githubusercontent.com/22717950/221440070-2c785cef-3864-4510-83b3-d2b95744e90e.png)

I got an issue when I first spawn when the player already loaded everything fine, but when first spawn xPlayer was not ready to read so I got the issue. I'm using multicharacter and I thing that is the issue

2023-02-27 09:35 UTC, Gellipapa commented
> 

I also use multicharacter, I don't understand what first spawn is. So when you see your character you already have xPlayer so you will getMeta as well as other xPlayer function. It won't before since you get xPlayer in the playerLoad event.

2023-02-27 09:36 UTC, Gellipapa commented
I assume you mean when you're in the "lobby" or when you're choosing a character. There will be no xPlayer there yet so yes getMeta will not work as well as xPlayer.identifier because xPlayer is nil.

2023-02-27 09:40 UTC, Gellipapa commented
If you still don't have this problem, write down a sequence of reproducible steps that we can use to trigger the problem.

2023-02-27 09:42 UTC, CsokiHUN commented
For multicharacter, as long as the player is not spawned, only the character is in the selector, xPlayer has no value in my opinion

2023-02-28 17:42 UTC, gerung commented
> I assume you mean when you're in the "lobby" or when you're choosing a character. There will be no xPlayer there yet so yes getMeta will not work as well as xPlayer.identifier because xPlayer is nil.
> 
> If this is your problem you will have to write a database query to get the meta data. It's like a column that can be queried by just json.decode the contents of the column to get a usable LUA table that you can index later.

agree, but currently, i don't have any idea how to do this, if you have sample metadata on multicharacter give me some logic, thx

2023-03-01 05:42 UTC, gerung commented
> I assume you mean when you're in the "lobby" or when you're choosing a character. There will be no xPlayer there yet so yes getMeta will not work as well as xPlayer.identifier because xPlayer is nil.
> 
> If this is your problem you will have to write a database query to get the meta data. It's like a column that can be queried by just json.decode the contents of the column to get a usable LUA table that you can index later.

solved, thanks

2023-03-01 08:31 UTC, gerung commented
@Rav3n95 is there an option to run on the client side?

2023-03-01 10:34 UTC, gerung commented
@Rav3n95 is there any option to get meta on client side?

2023-03-01 10:35 UTC, Rav3n95 commented
If you are using Legacy it's synced into Playerdata

2023-03-03 19:10 UTC, gerung commented
> ```lua
> getMeta
> ```

and it's possible to update from client side?

2023-03-05 09:22 UTC, ucingoyen commented
i have issue when set the meta, for example i have this meta on db
`{"chardata":{"dateofbirth":"2023-03-14","height":100,"injail":0,"isdead":false,"firstname":"Herman","ishandcuffed":false,"lastname":"Ringgo","ispunishment":0,"sex":"m"}}`
and trying to test with this command
```lua
RegisterCommand('test', function(source)
    local src = source
    local xPlayer = ESX.GetPlayerFromId(src)
    xPlayer.setMeta('chardata', 'ishandcuffed', true)
end, true)
```
but the meta changed like this `{"chardata":{"ishandcuffed":true}}`

hmm

2023-03-05 09:45 UTC, Rav3n95 commented
Are you using the Dev branch of esx?

2023-03-05 09:56 UTC, ucingoyen commented
> Are you using the Dev branch of esx?

no, using the "Main" esx

2023-03-05 10:10 UTC, Rav3n95 commented
It's not even on the main yet

2023-03-05 10:17 UTC, ucingoyen commented
> It's not even on the main yet

i just tried your metadata on main esx

2023-03-05 10:43 UTC, Rav3n95 commented
You forgot to copy something then, cuz it's already been use on a live server

2023-03-05 14:20 UTC, Gellipapa commented
[es_extended_currenty_dev.zip](https://github.com/esx-framework/esx_core/files/10892002/es_extended_currenty_dev.zip)

@ucingoyen Hi! Download this zip and drag and drop and overwrite your es_extended(but make backup save) this is include metadata system.