refactor(esx_identity): jquery removal
esx-framework/esx_core pull request #934
Opened 2023-03-11 13:31 UTC by MoskalykA

2023-03-11 13:35 UTC, Flambaa requested changes

2023-03-11 13:35 UTC, Flambaa commented on [core]/esx_identity/html/css/style.css
> +
Empty Space

2023-03-11 13:35 UTC, Flambaa commented on [core]/esx_identity/html/css/style.css
> +
+ Empty Space

2023-03-14 22:00 UTC, CsokiHUN approved these changes
looks good, thanks

2023-03-24 21:48 UTC, Gellipapa commented
@MoskalykA Why closed this pr?

2023-03-24 22:17 UTC, MoskalykA commented
> @MoskalykA Why closed this pr?

I deleted the fork to make another pull request, I had forgotten that it delete the other pull requests

2023-03-26 20:49 UTC, bitpredator approved these changes

2023-05-27 08:35 UTC, merged