feat(esx_identity/locales) Added IT locale
esx-framework/esx_core pull request #964
Opened 2023-03-21 18:06 UTC by NikartikTheBear

2023-03-21 18:35 UTC, Thekuca requested changes
Typo at the end of the 7th line. Please fix and thanks for the PR.

2023-03-21 20:25 UTC, NikartikTheBear commented
corrected the typo, thanks for the heads up

2023-03-22 06:37 UTC, Thekuca commented
Great, someone will merge it later.

2023-03-22 16:44 UTC, bitpredator approved these changes

2023-03-26 16:10 UTC, merged